; Script generated by Inno Setup Script Wizard.

#define MyAppName "Albion Trade Bot"
#define MyAppVersion "0.0.35"
#define MyAppPublisher "Mapi Developer"
#define MyAppExeName "AlbionTradeBot.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
AppId={{c362c6a4-c152-467b-9f3d-b6f8d659d1cb}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputDir=Output
; Renamed output file to indicate it bundles dependencies
OutputBaseFilename=AlbionTradeBot_Setup_Bundled
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; 1. The Main Application Files
; Copies everything from the built dist/AlbionTradeBot folder
Source: "dist\AlbionTradeBot\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; 2. The Dependency Installers
; These assume you have a folder named 'redist' in your project root (two levels up from this .iss file)
; They are copied to a temporary folder ({tmp}) and deleted after installation
Source: "redist\npcap_installer.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "redist\tesseract_installer.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; 1. Install Npcap
; Flags: 
;   waituntilterminated: Pauses the main setup until Npcap installer closes.
;   runascurrentuser: Ensures it runs with appropriate permissions.
;   skipifdoesntexist: Prevents errors if the file name changes slightly.
Filename: "{tmp}\npcap_installer.exe"; StatusMsg: "Installing Npcap (Required for Packet Sniffing)..."; Flags: waituntilterminated skipifdoesntexist runascurrentuser

; 2. Install Tesseract OCR
Filename: "{tmp}\tesseract_installer.exe"; StatusMsg: "Installing Tesseract OCR (Required for Text Recognition)..."; Flags: waituntilterminated skipifdoesntexist runascurrentuser

; 3. Launch the Main Application
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[Dirs]
; Ensure the config directory is writable for the user (important for your settings/logs)
Name: "{app}\config"; Permissions: users-modify