; Script generated by Inno Setup Script Wizard.

#define MyAppName "Market Trader"
#define MyAppVersion "0.3.0"
#define MyAppPublisher "Mapi Developer"
#define MyAppExeName "MarketTrader.exe"

[Setup]
AppId={{c362c6a4-c152-467b-9f3d-b6f8d659d1cb}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
SetupIconFile=bot\config\app_icon.ico
OutputDir="dist\Output"
OutputBaseFilename=MarketTraderSetup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

; IMPORTANT: This tells Windows to reload environment variables after install
ChangesEnvironment=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\MarketTrader\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "redist\npcap_installer.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall
Source: "redist\tesseract_installer.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{tmp}\npcap_installer.exe"; StatusMsg: "Installing Npcap (Required for Packet Sniffing)..."; Flags: waituntilterminated skipifdoesntexist runascurrentuser
Filename: "{tmp}\tesseract_installer.exe"; StatusMsg: "Installing Tesseract OCR (Required for Text Recognition)..."; Flags: waituntilterminated skipifdoesntexist runascurrentuser

[Dirs]
Name: "{app}\config"; Permissions: users-modify

[Code]
const
  // This is the default installation path for Tesseract.
  // If your installer puts it somewhere else, change this line.
  TesseractPath = 'C:\Program Files\Tesseract-OCR';

// Function to append the directory to the PATH variable
procedure AddToPath(PathToAdd: string);
var
  RegPath: string;
  OldPath: string;
  NewPath: string;
begin
  // We check the SYSTEM path (requires Admin). Use HKEY_CURRENT_USER if you only want it for the current user.
  RegPath := 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment';

  // 1. Get the current PATH value
  if RegQueryStringValue(HKEY_LOCAL_MACHINE, RegPath, 'Path', OldPath) then
  begin
    // 2. Check if Tesseract is already in the path to avoid duplicates
    if Pos(';' + PathToAdd, ';' + OldPath) = 0 then
    begin
      // 3. Append the new path
      // Handle case where path doesn't end with a semicolon
      if (OldPath <> '') and (OldPath[Length(OldPath)] <> ';') then
        NewPath := OldPath + ';' + PathToAdd
      else
        NewPath := OldPath + PathToAdd;

      // 4. Write the new path back to the registry
      RegWriteExpandStringValue(HKEY_LOCAL_MACHINE, RegPath, 'Path', NewPath);
    end;
  end;
end;

// Event that triggers after the installation steps are done
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    // Attempt to add Tesseract to the path
    try
      AddToPath(TesseractPath);
    except
      // If it fails (e.g. permissions), we ignore it so setup doesn't crash
      Log('Failed to add Tesseract to PATH.');
    end;
  end;
end;