# Operations
OP_GET_MAIL_INFOS = 1
OP_READ_MAIL = 3
OP_AUCTION_GET_OFFERS = 75
OP_AUCTION_GET_REQUESTS = 76
OP_EVENT_UPDATE_SILVER = 81
OP_EVENT_INVENTORY_MOVE_ITEM = 26
OP_EVENT_PLAYER_JOIN = 348
OP_EVENT_PLAYER_EQUIPMENT = 90
OP_EVENT_ISLAND_ENTER = 224
OP_JOIN_FINISHED = 2             # Initial Join
OP_NEW_CHARACTER = 29            # Player/Mob appeared
OP_INVENTORY_PUT_ITEM = 26       # Loot/Buy/Move (Add item to slot)
OP_INVENTORY_DELETE_ITEM = 27    # Sell/Trash/Move (Remove item from slot)
OP_INVENTORY_STATE = 28          # Full Inventory Sync
EVENT_NEW_ITEM = 30
OP_CHARACTER_EQUIPMENT_CHANGED = 90
OP_MOVE_REQUEST = 21
OP_LOCATION_CHANGED = 35
EVENT_RESOURCE = 39
EVENT_NEW_TRAVEL_POINT = 212

GAME_PORT = 5056

# Commands
COMMAND_SEND_RELIABLE = 6
COMMAND_SEND_FRAGMENT = 8

# Protocol Types
TYPE_NIL = 42
TYPE_DICTIONARY = 68
TYPE_STRING_ARRAY = 97
TYPE_INT8 = 98
TYPE_DOUBLE = 100
TYPE_EVENT_DATA = 101
TYPE_FLOAT32 = 102
TYPE_HASHTABLE = 104
TYPE_INT32 = 105
TYPE_INT16 = 107
TYPE_INT64 = 108
TYPE_INT32_ARRAY = 110
TYPE_BOOLEAN = 111
TYPE_OPERATION_RESPONSE = 112
TYPE_OPERATION_REQUEST = 113
TYPE_STRING = 115
TYPE_INT8_ARRAY = 120
TYPE_ARRAY = 121
TYPE_OBJECT_ARRAY = 122